#PASTE YOUTUBE PLAYLIST ID'S HERE, PLEASE DONT FORGET THE COMMAS
playlists = [
	#synthwave radio
	"PLkcA3mJSVisBLbLhQ6ZnTCi9nGHTVUDaI",
	# minecraft ost
	"PLefKpFQ8Pvy5aCLAGHD8Zmzsdljos-t2l",
	# NPC MUSIC
	"PL1jD2rtIo_9DVZ0xFQfE8Fxo6JG2gGzbo"
]