[
    {
        "name": "Rockstar",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "538txyi52ZOwzWxIQsCT12",
        "uri": "spotify:track:538txyi52ZOwzWxIQsCT12",
    },
    {
        "name": "IDGAF (with blackbear)",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "4ZUpTMKPYFTfJqamWFU9Zv",
        "uri": "spotify:track:4ZUpTMKPYFTfJqamWFU9Zv",
    },
    {
        "name": "Problematic",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "0I2BCIvlzrb6Iix9hAbQFF",
        "uri": "spotify:track:0I2BCIvlzrb6Iix9hAbQFF",
    },
    {
        "name": "Sick of U (with Oliver Tree)",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "5IXdkgrT4lb9sKIb8tbOQ3",
        "uri": "spotify:track:5IXdkgrT4lb9sKIb8tbOQ3",
    },
    {
        "name": "Two Moons",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "5GxUKIEkMXXZo1Tif0IzfC",
        "uri": "spotify:track:5GxUKIEkMXXZo1Tif0IzfC",
    },
    {
        "name": "Toxic",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "3M214U0mwSm041GsQR3nrO",
        "uri": "spotify:track:3M214U0mwSm041GsQR3nrO",
    },
    {
        "name": "Migraine",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "4YLKHaxYieIw6iMVfIvKm7",
        "uri": "spotify:track:4YLKHaxYieIw6iMVfIvKm7",
    },
    {
        "name": "Out Of Reach",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "5nXCKYd6lt9gO7AhZPv6Wh",
        "uri": "spotify:track:5nXCKYd6lt9gO7AhZPv6Wh",
    },
    {
        "name": "idtwcbf (friends)",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "4FAdGJxiagKwaF2d8ER1dn",
        "uri": "spotify:track:4FAdGJxiagKwaF2d8ER1dn",
    },
    {
        "name": "Understand",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "6dGqGkYDoRrKh5UiIcTT22",
        "uri": "spotify:track:6dGqGkYDoRrKh5UiIcTT22",
    },
    {
        "name": "Before I Die",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "0AncRT48nfh60LfQO2ZKR9",
        "uri": "spotify:track:0AncRT48nfh60LfQO2ZKR9",
    },
    {
        "name": "LoveSick",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "1zS5TccQwMDp5ZsEnt4FAh",
        "uri": "spotify:track:1zS5TccQwMDp5ZsEnt4FAh",
    },
    {
        "name": "Psycho",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "5zvYqhNLM9tmlbwhlGgf9r",
        "uri": "spotify:track:5zvYqhNLM9tmlbwhlGgf9r",
    },
    {
        "name": "Long Drives",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "1APefTkgjjwQfZbUWQkOFc",
        "uri": "spotify:track:1APefTkgjjwQfZbUWQkOFc",
    },
    {
        "name": "Bad Things",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "64L0htVknkRYCI1Q4ybiPI",
        "uri": "spotify:track:64L0htVknkRYCI1Q4ybiPI",
    },
    {
        "name": "Loafers",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "0jcPxc7Fme2oYb2MfFkOy6",
        "uri": "spotify:track:0jcPxc7Fme2oYb2MfFkOy6",
    },
    {
        "name": "Nosedive",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "4v7IE994aBZEjlo2tzZnhQ",
        "uri": "spotify:track:4v7IE994aBZEjlo2tzZnhQ",
    },
    {
        "name": "Prairies (with mxmtoon)",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "7w2iqaRxQgAGnkOdMhsiqu",
        "uri": "spotify:track:7w2iqaRxQgAGnkOdMhsiqu",
    },
    {
        "name": "Nightmare",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "7jI4rSFlLcVmSB00iTLqU5",
        "uri": "spotify:track:7jI4rSFlLcVmSB00iTLqU5",
    },
    {
        "name": "Blurry Nights",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "1GYPKqzuyRUsFstDrgVuWo",
        "uri": "spotify:track:1GYPKqzuyRUsFstDrgVuWo",
    },
    {
        "name": "Trauma",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "48JqgW96LVIcrE4umJweWw",
        "uri": "spotify:track:48JqgW96LVIcrE4umJweWw",
    },
    {
        "name": "She Said No",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "7k5b0qVGM007o03HAMYY7p",
        "uri": "spotify:track:7k5b0qVGM007o03HAMYY7p",
    },
    {
        "name": "Blue",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "3hhEuf4B60QLQDXRqGesS6",
        "uri": "spotify:track:3hhEuf4B60QLQDXRqGesS6",
    },
    {
        "name": "Falling for You",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "0ymYPgVwNv1GdORWEiQzUz",
        "uri": "spotify:track:0ymYPgVwNv1GdORWEiQzUz",
    },
    {
        "name": "Shy",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "2Uw7W4GRfkANPlBETf0DVO",
        "uri": "spotify:track:2Uw7W4GRfkANPlBETf0DVO",
    },
    {
        "name": "I Won’t Let You Go",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "6GUDmYitXops9vEcvYlu0J",
        "uri": "spotify:track:6GUDmYitXops9vEcvYlu0J",
    },
    {
        "name": "Small Fry",
        "artist": "Curio Watts",
        "type": "track",
        "id": "33OLThvziIdbRIwxNDj4gf",
        "uri": "spotify:track:33OLThvziIdbRIwxNDj4gf",
    },
    {
        "name": "Tired of Wanting You",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "1OCBFqKr3OX0PdwwmtlWGY",
        "uri": "spotify:track:1OCBFqKr3OX0PdwwmtlWGY",
    },
    {
        "name": "Hazel Eyes",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "2P375Ek8tXZjgo0bef9Sc1",
        "uri": "spotify:track:2P375Ek8tXZjgo0bef9Sc1",
    },
    {
        "name": "Zoning Out",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "2j5Wq9YmuPETRJjsnsfAYa",
        "uri": "spotify:track:2j5Wq9YmuPETRJjsnsfAYa",
    },
    {
        "name": "Animal Crackers",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "0l3cY7XlX97MWxkxey5fQJ",
        "uri": "spotify:track:0l3cY7XlX97MWxkxey5fQJ",
    },
    {
        "name": "Out of Tune",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "2Ouu07dJ1tUavnkARWsdJ9",
        "uri": "spotify:track:2Ouu07dJ1tUavnkARWsdJ9",
    },
    {
        "name": "Route 9",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "74pMcjz0Wm2D3Sve5P9SkB",
        "uri": "spotify:track:74pMcjz0Wm2D3Sve5P9SkB",
    },
    {
        "name": "Sleep Deprived",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "7xdyIjQ4qX7iSL6E5qqyHX",
        "uri": "spotify:track:7xdyIjQ4qX7iSL6E5qqyHX",
    },
    {
        "name": "Lovely",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "5Q9Cp5K3qOgslZDnIAuVqw",
        "uri": "spotify:track:5Q9Cp5K3qOgslZDnIAuVqw",
    },
    {
        "name": "I Wish",
        "artist": "BoyWithUke",
        "type": "track",
        "id": "0BUxAlVFVTpfl31Vr9byBT",
        "uri": "spotify:track:0BUxAlVFVTpfl31Vr9byBT",
    },
]
